//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CurrencyExchangeNet5MVC.Resources.Views.Home {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Index_ar {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index_ar() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("CurrencyExchangeNet5MVC.Resources.Views.Home.Index.ar", typeof(Index_ar).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string TitleWhatIsTola {
            get {
                return ResourceManager.GetString("TitleWhatIsTola", resourceCulture);
            }
        }
        
        internal static string DescriptionWhatIsTola {
            get {
                return ResourceManager.GetString("DescriptionWhatIsTola", resourceCulture);
            }
        }
        
        internal static string TitleWhatIsAnOunce {
            get {
                return ResourceManager.GetString("TitleWhatIsAnOunce", resourceCulture);
            }
        }
        
        internal static string DescriptionWhatIsAnOunce {
            get {
                return ResourceManager.GetString("DescriptionWhatIsAnOunce", resourceCulture);
            }
        }
        
        internal static string TitleTolaGrams {
            get {
                return ResourceManager.GetString("TitleTolaGrams", resourceCulture);
            }
        }
        
        internal static string DescriptionTolaGrams {
            get {
                return ResourceManager.GetString("DescriptionTolaGrams", resourceCulture);
            }
        }
        
        internal static string TitleKgTola {
            get {
                return ResourceManager.GetString("TitleKgTola", resourceCulture);
            }
        }
        
        internal static string DescriptionKgTola {
            get {
                return ResourceManager.GetString("DescriptionKgTola", resourceCulture);
            }
        }
        
        internal static string TitleTolaCountries {
            get {
                return ResourceManager.GetString("TitleTolaCountries", resourceCulture);
            }
        }
        
        internal static string DescriptionTolaCountries {
            get {
                return ResourceManager.GetString("DescriptionTolaCountries", resourceCulture);
            }
        }
        
        internal static string MetaDescription {
            get {
                return ResourceManager.GetString("MetaDescription", resourceCulture);
            }
        }
    }
}
